data <- read.table("household_power_consumption.txt", header = TRUE, stringsAsFactors = FALSE, sep = ";")
sub <- data[data$Date %in% c("1/2/2007", "2/2/2007") , ]
global <- as.numeric(sub$Global_active_power)
sub1 <- as.numeric(sub$Sub_metering_1)
sub2 <- as.numeric(sub$Sub_metering_2)
sub3 <- as.numeric(sub$Sub_metering_3)
date <- strptime(paste(sub$Date, sub$Time, sep = " "), "%d/%m/%Y %H:%M:%S")
png("Plot3.png", width = 480, height = 480)
plot(date, sub1, xlab = "" , ylab = "Energy sub metering",type = 'l')
lines(date, sub2,col = "red")
lines(date, sub3, col = "blue")
legend("topright", col = c("black", "red", "blue"), lty = 1, c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()